package com.lendingclub.model;

/**
 * Created by tmichels on 12/8/14.
 */
public enum ExecutionStatus {

    ORDER_FULFILLED("ORDER_FULFILLED"),
    LOAN_AMNT_EXCEEDED("LOAN_AMNT_EXCEEDED"),
    NOT_AN_IN_FUNDING_LOAN("NOT_AN_IN_FUNDING_LOAN"),
    REQUESTED_AMNT_LOW("REQUESTED_AMNT_LOW"),
    REQUESTED_AMNT_ROUNDED("REQUESTED_AMNT_ROUNDED"),
    AUGMENTED_BY_MERGE("AUGMENTED_BY_MERGE"),
    ELIM_BY_MERGE("ELIM_BY_MERGE"),
    INSUFFICIENT_CASH("INSUFFICIENT_CASH"),
    MAX_AMNT_PER_LOAN_EXCEEDED("MAX_AMNT_PER_LOAN_EXCEEDED"),
    MAX_PERCENT_PER_LOAN_EXCEEDED("MAX_PERCENT_PER_LOAN_EXCEEDED"),
    MAX_PERCENT_PER_LOAN_TIME_EXCEEDED("MAX_PERCENT_PER_LOAN_TIME_EXCEEDED"),
    MAX_AMNT_PER_LOAN_TIME_EXCEEDED("MAX_AMNT_PER_LOAN_TIME_EXCEEDED"),
    NOT_AN_INVESTOR("NOT_AN_INVESTOR"),
    NOTE_ADDED_TO_PORTFOLIO("NOTE_ADDED_TO_PORTFOLIO"),
    NOT_A_VALID_PORTFOLIO("NOT_A_VALID_PORTFOLIO"),
    ERROR_ADDING_NOTE_TO_PORTFOLIO("ERROR_ADDING_NOTE_TO_PORTFOLIO"),
    SYSTEM_BUSY("SYSTEM_BUSY");

    final String executionStatus;

    ExecutionStatus(String executionStatus){
        this.executionStatus = executionStatus;
    }
}
